/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resourcemanagementsystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class UserDashboard extends javax.swing.JFrame {

   String line,Name=null,Gender=null,AccountType=null,Email=null,Password=null,Contact=null,Role=null,Age=null;
   
   Random r=new Random();
    public UserDashboard() {
        initComponents();
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        role = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        applicant = new javax.swing.JTextField();
        days = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        reason = new javax.swing.JTextField();
        submitapplication = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        myapplication = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ApplicationType = new javax.swing.JComboBox<>();
        close = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(733, 513));
        setPreferredSize(new java.awt.Dimension(733, 513));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("User Panel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 195, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Submit application");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 210, 270, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 250, 40, 20);
        getContentPane().add(name);
        name.setBounds(160, 250, 150, 30);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(160, 290, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 290, 70, 20);

        update.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(180, 450, 110, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Contact:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 330, 60, 20);
        getContentPane().add(contact);
        contact.setBounds(160, 330, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Role:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 370, 40, 20);
        getContentPane().add(role);
        role.setBounds(160, 370, 150, 30);
        getContentPane().add(age);
        age.setBounds(160, 410, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Age:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 410, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Application type:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 300, 110, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Applicant name:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 340, 110, 15);
        getContentPane().add(applicant);
        applicant.setBounds(490, 340, 150, 30);
        getContentPane().add(days);
        days.setBounds(490, 380, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("No. of Days:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 380, 80, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ID:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(450, 260, 50, 15);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(490, 260, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Reason:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(430, 430, 70, 15);
        getContentPane().add(reason);
        reason.setBounds(490, 420, 260, 60);

        submitapplication.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        submitapplication.setText("Submit");
        submitapplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitapplicationActionPerformed(evt);
            }
        });
        getContentPane().add(submitapplication);
        submitapplication.setBounds(560, 490, 110, 30);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("My application");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Status");

        myapplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myapplicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(myapplication, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status)
                    .addComponent(myapplication))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 100, 270, 80);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Profile information");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 200, 270, 40);

        ApplicationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation", "Emergency", "Occasion", "Sickness" }));
        ApplicationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplicationTypeActionPerformed(evt);
            }
        });
        getContentPane().add(ApplicationType);
        ApplicationType.setBounds(490, 300, 150, 22);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcemanagementsystem/close (1).png"))); // NOI18N
        close.setText("   Exit");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(20, 20, 110, 50);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcemanagementsystem/logout.png"))); // NOI18N
        logout.setText("  Logout?");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(650, 20, 160, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        try{
            
            File temp = new File(".txt");
            File original = new File("registration.txt");
            FileWriter fwtemp = new FileWriter(".txt");
            BufferedWriter bwtemp = new BufferedWriter(fwtemp);
            FileReader fr = new FileReader("registration.txt");
            BufferedReader br = new BufferedReader(fr);
            String srch = Email;
            String line = null;
            int edit = 0;
            while ((line=br.readLine()) != null)
                {
                    if(line.contains(srch))
                    {

                       String data = name.getText()+","+Gender+","+AccountType+","+Email+","+password.getText()+","+contact.getText()+","+role.getText()+","+age.getText();
                        bwtemp.write(data);  
                        bwtemp.write(System.getProperty("line.separator"));
                        edit=1;
                    }else
                    {
                        bwtemp.write(line);
                        bwtemp.newLine();
                    }
                }
            if(edit == 1)
            {
                JOptionPane.showMessageDialog(null, "Record is successfully Updated");
            }else
            {
                JOptionPane.showMessageDialog(null, "Record not found");
            }
             br.close();
             br=null;
            bwtemp.close();
            bwtemp=null;
            fr.close();
            fr=null;
            fwtemp.close();
            fwtemp=null; 
            original.delete();
            temp.renameTo(original); 
            }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error Message");
        }
        
       name.setText("");
        role.setText("");
        age.setText("");
        contact.setText("");
        password.setText("");
        
     
    }//GEN-LAST:event_updateActionPerformed

    private void submitapplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitapplicationActionPerformed
        
        try{
         String status="Under process";
         String ID=id.getText();
         String Applicant=applicant.getText();
         String Days=days.getText();
         String Reason=reason.getText();
         
         FileWriter d=new FileWriter("applications.txt",true);  //write data in departments file
         String data = ID+","+ApplicationType.getSelectedItem()+","+Applicant+","+Email+","+Days+","+Reason+","+status;
         d.write(data);
         d.write(System.getProperty("line.separator"));
         d.close();
         JOptionPane.showMessageDialog(null,"Application Submitted Successfully");         
       }
       catch(Exception e){        //exception handling
       JOptionPane.showMessageDialog(null,e);
       }
       setApplicationID();
       days.setText("");
       reason.setText("");
         
    }//GEN-LAST:event_submitapplicationActionPerformed

    private void myapplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myapplicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myapplicationActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void ApplicationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplicationTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApplicationTypeActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Resource Management System...",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed
     void setApplicationID(){
         int n=r.nextInt(500)+1;
         
         id.setText(String.valueOf(n));
     }
     void viewData(String Username) {
        
        String user=null;
        user=Username;
   //Show user profile data
         try {
             FileReader fr = new FileReader("registration.txt");
             BufferedReader br = new BufferedReader(fr);
             
             while ((line = br.readLine()) != null) {
                 String[] details=new String[8];
                 details = line.split(",");
                 Name = details[0];
                 Gender = details[1];
                 AccountType = details[2];
                 Email = details[3];
                 Password = details[4];
                 Contact = details[5];
                 Role = details[6];
                 Age = details[7];
                 if (Email.equals(user)) {
                     name.setText(Name);
                     password.setText(Password);
                     contact.setText(Contact);
                     role.setText(Role);
                     age.setText(Age);
                     applicant.setText(Name);
                     break;
                 }
             }
                
            fr.close();
    }catch(Exception e){
    e.printStackTrace();
        }
         
         try {
            FileReader fr = new FileReader("ApprovedRejected.txt");
            BufferedReader br = new BufferedReader(fr);
           while ((line = br.readLine())!= null) {
            String ApplicationType= line.split(",")[1];
            String namee= line.split(",")[3];
             String   ApplicationStatus = line.split(",")[7];
                if (namee.equals(user)) {
                       myapplication.setText(ApplicationType);
                       status.setText(ApplicationStatus);
                        
                } 
           }
                
            fr.close();
    }catch(Exception e){
    e.printStackTrace();
        }

 //Show user application data
        try {
            FileReader fr = new FileReader("applications.txt");
            BufferedReader br = new BufferedReader(fr);
           while ((line = br.readLine())!= null) {
            String ApplicationType= line.split(",")[1];
            String namee= line.split(",")[3];
             String   ApplicationStatus = line.split(",")[7];
                if (namee.equals(user)) {
                       myapplication.setText(ApplicationType);
                       status.setText(ApplicationStatus);
                        
                } 
           }
                
            fr.close();
    }catch(Exception e){
    e.printStackTrace();
        }
     }
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ApplicationType;
    private javax.swing.JTextField age;
    private javax.swing.JTextField applicant;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField days;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField myapplication;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField reason;
    private javax.swing.JTextField role;
    private javax.swing.JTextField status;
    private javax.swing.JButton submitapplication;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
